#!/bin/bash
# Created by 
fi
last | grep ppp | grep still | awk '{print " ",$1," - " $3 }' > /tmp/login-db-pptp.txt;
echo "Script by vps-murah.net"
echo "Terimakasih sudah berlangganan di vps-murah.net"
echo "===============================================";
echo " "
echo " "
echo "Memeriksa User PPTP VPN Yang Login";
echo "(Username - IP)";
echo "-------------------------------------";
cat /tmp/login-db-pptp.txt
echo " "
echo " "
echo " "
echo "===============================================";
echo "Script Created by http://seller-vps.net";
echo "Terimakasih sudah berlanggan di seller-vps.net";